name = "MetaAnalysis"
uuid = "09521429-32ac-4aec-8e5f-91f1cf1e3144"
authors = ["Arindam Basu"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"

[compat]
julia = "1.9.0"
DataFrames = "1.5.0"
GLM = "1.8.3"
HypothesisTests = "0.11.0"
Distributions = "0.25.97"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
